import Head from "next/head";
import Nav from "../comonents/Nav";
import PostItem from "../comonents/PostItem";
import { Layout } from "../styles";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <nav>
          <Nav />
        </nav>
        <main>
          <PostItem />
        </main>
      </Layout>
      {/* <footer>Footer</footer> */}
    </div>
  );
}
